/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/3d/marcus_aurelius/scene.gltf --transform 
Files: ./public/3d/marcus_aurelius/scene.gltf [29.14KB] > C:\hursun\Unfazed-web\scene-transformed.glb [4.46MB] (-15215%)
Author: The British Museum (https://sketchfab.com/britishmuseum)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/marcus-aurelius-36fd581851294110a7eda08ec2a20748
Title: Marcus Aurelius
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.model} rotation={[2.695, 0.045, 1.425]} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
